### PR TITLE
Refactor/docker

### PR DESCRIPTION
**Pull request by Yuhanun**
Changed the travis builds to now use a docker image with pre-built dependencies.

Created a docker folder which contains the dockerfile used to generate the image. Dependencies for this: docker.io, docker-compose.

Create a .sh file with the repo's name if you want to add a repo to travis and just copy the template over from one of the other repos + replace the repo name + test name

### CODE REVIEW

**Comment by Yuhanun** [comment]
Now also handles issue #1

**Comment by emielsteerneman** [comment]
What are the intense amount of changes in all the other repos?

**Comment by Yuhanun** [comment]
> What are the intense amount of changes in all the other repos?

What do you mean?

**Comment by Yuhanun** [comment]
It's cause I do git add . 

dammit...

How do I undo these changes?

**Comment by Yuhanun** [comment]
Know what, I'll re-do this...

**Pull request closed without merging**
